### ISSUE TITLE
Import feature?

### ISSUE THREAD

**Issue by jschomay** [erkal/kite#4]
Very cool tool!  I've been using online graphviz projects like https://dreampuf.github.io/ for many uses, but I would like more interactivity, such as what you provide.

I saw a plan for exporting different formats, but how about import DOT format?  Or at least have a DOT editor.  I find it easier to create graphs (especially when I want to specify labels/colors/etc) that way.  Also, most graph libraries can export to different formats such as DOT (this is true for the elm graph library too - I'm the one who originally added it!).

Thanks for considering this feature, and great work!

**Comment by erkal** [comment]
Thank you for the nice words.
Kite uses [elm-community/graph](https://package.elm-lang.org/packages/elm-community/graph/latest). So thank you for contributing to that package!
You could place a "DOT file import/export window" just below the "Elm Module Dependency import window":
![image](https://user-images.githubusercontent.com/2286325/52521938-4a44c380-2c7f-11e9-9554-5e5e59e60bd0.png)
I would merge it if you would make a pull request.
Otherwise, I can do it myself (but it can take time because I don't have so much time for Kite right now).

**Comment by erkal** [comment]
It looks like we need a parser for [the DOT Language](https://www.graphviz.org/doc/info/lang.html).
It makes then sense to do it as an independent elm package and publish it.

**Comment by brandly** [comment]
i wrote [a DOT parser](https://github.com/brandly/elm-dot-lang/blob/master/src/DotLang.elm). 

it has a few TODOs still. i think the main issue is it can't parse HTML nodes, and it can't handle arbitrarily placed comments. i looked at [this package](https://package.elm-lang.org/packages/hecrj/html-parser/latest/) for html parsing, but it only exposes the `run` function and i think i want [this internal `node` definition](https://github.com/hecrj/html-parser/blob/1e9f6d3b19b736f66713a930ba9d6f9a1c060aea/src/Html/Parser.elm#L57-L63). 

i've never written a serious parser in Elm, so maybe @jinjor or someone could look it over.

**Comment by erkal** [comment]
Great! 
The biggest thing was writing the parser. :)
I cannot comment on the parser because I also have never written a serious parser. But I am sure that it is good.

**Comment by brandly** [comment]
thanks to @hecrj, i think the parser is thoroughly implemented now! i plan to do more testing and write some comments/docs, but we should be able to move forward on this feature soon.

**Comment by erkal** [comment]
🎉I don't know much about parsers but the code looks very clean and nice.

I am not going to be able to work on this for a while. Of course, if you make a pull request, I will merge.

I never used [elm/file](https://package.elm-lang.org/packages/elm/file/1.0.4/) but it looks like the library to use. Or maybe just a text field?

**Comment by brandly** [comment]
here's what i'm thinking:

* we need `Dot -> Graph` for importing
* we need `Graph -> Dot` and `Dot -> String` for exporting. 
* `toString : Dot -> String` can be part of my repo. i'm not sure where the `Dot`/`Graph` converters should live.
* `elm/file` would be good to integrate. a `<textarea>` might also be nice, for those who are familiar with DOT and can write it by hand. the `textarea` is easier to implement, so we could start there.

does that all sound right?

**Comment by jschomay** [comment]
The elm community graph package already has a few graph to * converters,
and you could probably just use those.

I think it makes sense to put the dot to graph converter in that repo too,
as that would be very useful.

**Comment by brandly** [comment]
i see [this `Graph -> String`](https://package.elm-lang.org/packages/elm-community/graph/latest/Graph-DOT), which means exporting to a DOT file already seems possible. (https://github.com/erkal/kite/pull/6)

my repo could also have a `DOT -> String`, since i'm under the impression `DOT` can represent more visually than `Graph`. this wouldn't be a priority for Kite tho.

@sgraf812 are you interested in [`graph`](https://github.com/elm-community/graph) having a `DOT -> Graph` converter? `Graph` feels more fundamental to me, and i don't have much sense of how likely you would need `DOT` if you're using `Graph`. i'm happy for it to live in my repo, but i'm not sure what's best!!

**Comment by sgraf812** [comment]
Hey, sorry to be so late to the discussion. I'm generally a little sceptical of adding any more importing/exporting functionality and think they should rather go in seperate packages. Things aren't so bad when it's just some hacky `Graph -> String` conversion, but depending on a package that defines the `Dot` language and a parser just doesn't feel right to me.

So: I'd be happy to see a function `Graph -> DOT` and `DOT -> Graph` and would deprecate the hacky `Graph.DOT` module in favor of it, but not as part of `elm-community/graph`.

**Comment by jschomay** [comment]
> not as part of elm-community/graph

If this functionality ends up in a separate package, I'd prefer it to be stand-alone (as opposed to a part of `kite`), so that I can use it along side of `elm-community/graph`.  I definitely have projects that use `Graph` that won't need `kite` that will need `DOT -> Graph`.

**Comment by brandly** [comment]
there's [some discussion here](https://github.com/erkal/kite/pull/6#issuecomment-471173227) where it looks like we'll be going between `GraphFile` and `DOT`, not just `Graph`, for Kite's purposes.

> So: I'd be happy to see a function Graph -> DOT and DOT -> Graph and would deprecate the hacky Graph.DOT module in favor of it, but not as part of elm-community/graph.

>  I definitely have projects that use Graph that won't need kite that will need DOT -> Graph.

i agree. this should exist. i'm not sure where it'll live.

i haven't published `DotLang` at all yet, but it's almost ready. once that happens, we'll probably write `GraphFile -> DOT` first. since `GraphFile` has a `Graph` within it, we'll _basically_ have a `Graph -> DOT` implementation, which we could then pull out of Kite into a separate package.

i'm glad that there's wider interest in these components!

**Comment by erkal** [comment]
> i haven't published DotLang at all yet, but it's almost ready. once that happens, we'll probably write GraphFile -> DOT first. since GraphFile has a Graph within it, we'll basically have a Graph -> DOT implementation, which we could then pull out of Kite into a separate package.

After you publish `DotLang`, I can write `GraphFile` -> `DOT` and `DOT` -> `GraphFile`.

I will try to do it in such a way, that the field names coincide with the property names that are used by GraphViz. So that, if one wants to transport his/her graph from Kite to Graphviz, this would be helpful.

**Comment by brandly** [comment]
thanks @erkal! i should have time to write out more docs and get it published soon.

i'll try to get an initial version out before writing `DOT -> String`, so we can build an importer. having you write `DOT -> GraphFile` will be a good exercise in seeing if `DOT`'s current implementation has any shortcomings. plus, i'm just excited to see someone else use it 😄 

after we see how that goes, i can add `DOT -> String`, and we should be able to build a nice exporter as well.

**Comment by brandly** [comment]
@erkal i [published `DotLang`](https://package.elm-lang.org/packages/brandly/elm-dot-lang/latest/DotLang)! i'm sure the docs aren't ideal yet, and maybe the AST itself could be improved. please [send me any suggestions you have](https://github.com/brandly/elm-dot-lang/issues/new).

i already added `DOT -> String`, so theoretically, we have everything we need to import/export DOT and to use DOT, instead of JSON, for graph serialization.

looking forward to seeing this come together!

**Comment by erkal** [comment]
Great! ❤️ 
The docs are ideal to me.
I will do the Kite side as soon as I find time.

**Comment by erkal** [comment]
Ok, now it is in [progress](https://github.com/erkal/kite/projects/1#column-3500751)

**Comment by brandly** [comment]
i see that `toDot` and `fromDot` are both checked off! are you working from a branch i could see?

**Comment by erkal** [comment]
I checked those boxes maybe too early. :) But I am going to push something in a couple of days. I will send you a message when I do.

**Comment by erkal** [comment]
Hey @brandly, I pushed a branch: [using-dotlang](https://github.com/erkal/kite/tree/using-dotlang)
It is not working yet, partly because of the issues I opened in [brandly/elm-dot-lang/issues](https://github.com/brandly/elm-dot-lang/issues).
So we made good progress 🎉 
I think we are done with the 99% of code if we restrict ourselves to the use of dot language inside Kite.
For importing `.dot` files that aren't exported by Kite, I think there is a lot of work to do. And also I see that there is no end to it: https://www.graphviz.org/doc/info/attrs.html
But we can extend in time, starting with the ones that are most used.

**Comment by brandly** [comment]
idea: since there will undoubtedly be graphviz properties that aren't first-class properties in Kite, we could hold these extraneous properties in a `Dict String String`. that way, we should be able to import a `.dot` file and then export an equivalent `.dot`, without losing those properties.

i haven't looked at how feasible this is at an implementation level. maybe it complicates things more than it's worth.

**Comment by erkal** [comment]
We already have `fromDot(toDot(g))` for all `g : GraphFile`. 
It is a good idea to have: `toDot(fromDot(d))` = `d` for all `d : Dot`.

But only a `Dict String String` may not be a good fit to keep all the other things like subgraphs that Kite does not read.
How about keeping a field: `dotFile : Dot` in [`GraphFile`](https://github.com/erkal/kite/blob/1650733080469476e66232ec1bbe501dac6d71b2/src/GraphFile.elm#L110-L114) and rewrite `toDot` in such a way, that it updates thid field?

**Comment by erkal** [comment]
Ok, the local storage uses now DotLang instead of json.
One can also export and import graphs as Dot files.
I am closing this issue.
I am going to open a new issue for the last problem above.
